### ISSUE TITLE
Get netstandard tests reported in AppVeyor UI

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#110]
Take a look at the comments here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test

Specifically regarding passing options to the underlying test adapter so we can customize the output format of the nunit tests for AppVeyor to display them in CI runs.

**Comment by masojus** [comment]
https://github.com/nunit/nunit3-vs-adapter/issues/215

**Comment by masojus** [comment]
It also looks like the VS adapter is indeed able to discover and run the tests in the VS UI. I wonder if directly using the `nunit3-console.exe` can run the `netstandard` tests and produce XML output.

**Comment by masojus** [comment]
https://www.appveyor.com/docs/running-tests/#pushing-real-time-test-results-to-build-console

**Comment by masojus** [comment]
At the moment not even the .NET Framework tests are being reported because we run them under OpenCover to gather coverage data and then don't upload the results.xml. Before, these tests were getting reported in the UI because we were using AppVeyor's *Auto* test discovery/execution.

**Comment by masojus** [comment]
To upload the netstandard tests, we might have to use the trx logger and upload to AppVeyor's reporting endpoint with `mstest` as the `resultsType`: https://github.com/dotnet/cli/issues/3114#issuecomment-291104000

**Comment by masojus** [comment]
Actually n/m, the .NET Framework tests *are* getting automatically reported because we output a filename and format AppVeyor knows about....we just weren't actually running those tests :/ That's fixed now, so what remains will be to see how we report the .NET Standard tests if/when we get rid of the big .NET Framework tests, which will likely only happen if we can report coverage for those too.

**Comment by baumatron** [comment]
This should be working now because of #124.
