### ISSUE TITLE
NetStandard code coverage

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#111]
Code coverage for `netstandard` projects still seems to be in flux and I wonder if OpenCover is capable of producing coverage...but I sort of doubt it for the moment since I've read that in general coverage wasn't working as of Spring this year. But there does seem to be a `Microsoft.CodeCoverage` NuGet package:

https://github.com/Microsoft/vstest/issues/579#issuecomment-287242343
https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md
https://www.nuget.org/packages/Microsoft.CodeCoverage/

...so will/does OpenCover or something similar implement a collector that works with these tools? And can that collector generate the report output format needed in order to parse/upload to Coveralls.io?

**Comment by masojus** [comment]
This seems to indicate that OpenCover works with .NET Standard test projects to some extent. The examples are all using xUnit: https://github.com/OpenCover/opencover/issues/721

**Comment by masojus** [comment]
This article also describes reporting Code Coverage using OpenCover on a .NET Core test project: https://blog.markvincze.com/setting-up-coveralls-for-a-net-core-project/

We'd have to do this once we move away from the .NET Framework projects completely, as I'm not sure how we'd report separately for the .NET Framework and .NET Standard test runs and get Coveralls to either merge those results or understand that there are two different coverage runs per commit.

**Comment by baumatron** [comment]
The `netstandard_coverage` branch has what appears to be working code coverage now for the netstandard project.

**Comment by baumatron** [comment]
This is working now and being reported by the AppVeyor build.

**Comment by thnk2wn** [comment]
@baumatron We are trying to use OpenCover with Cake build on a solution that uses .net standard. Any idea when this might be pushed as a prerelease nuget version so we can incorporate into Cake and our CI build? I'm not sure I can easily make Cake work with a local nuget package I download from AppVeyor but I can take a look.
