### ISSUE TITLE
Critical breaking bug in 0.3.3 ( AddOn Update )

### ISSUE THREAD

**Issue by Bio2hazard** [keenlabs/keen-sdk-net#12]
While most methods default the AddOn Array to null, this was omitted in PrepareUserObject @ https://github.com/keenlabs/keen-sdk-net/blob/master/Keen/KeenClient.cs#L337

This leads to any calls to AddEvent(collection, event) failing with "ArgumentNullException: Value cannot be null. Parameter name: source".

The only workaround currently is to call AddEvent(collection, event, new AddOn[0]);

**Comment by davidknaack** [comment]
Confirmed, fix on the way.

**Comment by davidknaack** [comment]
Updated, change should appear on Nuget shortly.
Thanks!
