### ISSUE TITLE
keenlabs/keen-sdk-net and rynnwang/KeenSDK

### ISSUE THREAD

**Issue by FantasticFiasco** [keenlabs/keen-sdk-net#15]
Both seems to be SDK:s for Keen IO. Which one is official and what are the differences between them?

**Comment by davidknaack** [comment]
This project keenlabs/keen-sdk-net is the official Keen IO .NET SDK (you can find links to this and other language SDKs in the Keen IO docs at https://keen.io/docs/SDKs/ ). The rynnwang/KeenSDK repository is a branch from here which has been customized to it's owner's needs. I don't know anything about it beyond that, you'd have to ask the maintainer for more details.
