### ISSUE TITLE
Funnel querys are missing several features available on other platforms

### ISSUE THREAD

**Issue by PolarbearDK** [keenlabs/keen-sdk-net#17]
FunnelStep class is missing with_actors, optional & inverted property.
Queries.Funnel method discards "actors" and "steps" from returned result (only "result" property are returned).

**Comment by PolarbearDK** [comment]
I have fixed this in my own branch, but it's a breaking change.

The return type is now: 
    public class FunnelResult
    {
        [JsonProperty(PropertyName = "actors", NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<IEnumerable<string>> Actors { get; set; }

        [JsonProperty(PropertyName = "result", NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<int> Result { get; set; }

        [JsonProperty(PropertyName = "steps", NullValueHandling = NullValueHandling.Ignore)]
        public IEnumerable<JObject> Steps { get; set; }
    }

To deserialize "Steps", I had to implement Json deserialization support for several classes as it were/is missing.

I'm facing a similar problem with Metric querys where the result is always a string, even if result is numeric. As I'm passing on the result to Keen.Io visualization this is important. 

Group by querys has a different but related problem. Each group is represented in json as:
{ "groupfieldname" : "groupvalue", result: 42} 
But only "groupvalue" and "result" are saved in QueryGroupValue<T> (and T is string which means loosing type information). The "groupfieldname" information is lost (removed by Keen's .NET client).

**Comment by davidknaack** [comment]
May I see your changes for steps? Maybe we can merge them in?

Do you have any thoughts on an approach to address the issue with numeric results?

**Comment by PolarbearDK** [comment]
I have elected to use my own method for querys using JObject as argument and return object. 

```csharp
public async Task<JObject> KeenWebApiRequest(string operation, JObject content)
{
    // Either an API read key or a master key is required
    var key = string.IsNullOrWhiteSpace(_prjSettings.MasterKey) ? _prjSettings.ReadKey : _prjSettings.MasterKey;
    if (string.IsNullOrWhiteSpace(key))
        throw new KeenException("An API ReadKey or MasterKey is required");

    var url = string.Format("{0}{1}",
        _serverUrl,
        string.IsNullOrWhiteSpace(operation) ? "" : "/" + operation);

    using (var client = new HttpClient())
    {
        client.DefaultRequestHeaders
            .Add("Authorization", key);
        client.DefaultRequestHeaders
            .Accept
            .Add(new MediaTypeWithQualityHeaderValue("application/json"));

        var stringContent = new StringContent(content.ToString(), Encoding.UTF8, "application/json");
        var responseMsg = await client.PostAsync(url, stringContent).ConfigureAwait(false);
        var responseString = await responseMsg.Content.ReadAsStringAsync().ConfigureAwait(false);
        var response = JObject.Parse(responseString);

        // error checking, throw an exception with information from the json 
        // response if available, then check the HTTP response.
        KeenUtil.CheckApiErrorCode((dynamic)response);
        if (!responseMsg.IsSuccessStatusCode)
            throw new KeenException("Request failed with status: " + responseMsg.StatusCode);

        return response;
    }
}

```

**Comment by davidknaack** [comment]
I've updated the funnel code to include the features referenced in the documentation.
