### ISSUE TITLE
Add example documentation for Queries

### ISSUE THREAD

**Issue by hex337** [keenlabs/keen-sdk-net#18]
It looks like there's code for query support, but there are no examples of how to run them!

**Comment by davidknaack** [comment]
You're right, I'll see what I can do to add some examples.

In the meantime you could probably get an idea of how to use it by looking at the tests.

Any suggestions for what you'd want to see for examples?

**Comment by hex337** [comment]
Could probably do a few sample queries pulled from the [open data collectors](https://github.com/keen/open-data-collectors/blob/master/README.md) project.

**Comment by matthieunelmes** [comment]
+1 for some Query documentation please!

**Comment by bootleg224** [comment]
Hope this helps someone:

//Add LicenseKey filter
var filters = new List<QueryFilter>();
            filters.Add(new QueryFilter("LicenseKey", QueryFilter.FilterOperator.Equals(), queryParameters.LicenseKey));

//Add Filter on Username
            if (!queryParameters.EmailOrUsername.IsNullOrEmpty())
            {
                filters.Add(new QueryFilter("Username", QueryFilter.FilterOperator.Equals(), queryParameters.EmailOrUsername.ToLower()));                
            }

//Go ahead and query the data, and get it out as a list of anonymous objects (by default it comes out as a dynamic)
            var data = keenClient.QueryExtractResource("CollectionName", new QueryAbsoluteTimeframe(DateTime.UtcNow.AddDays(-1 * queryParameters.NumberOfDays), DateTime.UtcNow), filters).Select(c => new
            {          
                Email = c.Email,
                FirstName = c.FirstName,
               LoginSuccessful = c.LoginSuccessful,
                Timestamp = c.keen.timestamp
            });

**Comment by bootleg224** [comment]
Also the "IN" operator talks about getting a Json array, but the API uses POCO objects, no need to serialize to JSON on your own

**Comment by elof** [comment]
@davidknaack would it be possible to get me a list of things that the SDK supports that are not documented? We definitely need to show what functionality is built.

**Comment by davidknaack** [comment]
@elof can you explain a bit more what you mean by things that are supported but not documented? 

The SDK tries to present a fairly one-to-one correspondence with the Keen.IO API documentation that was current at the time the SDK was written, so the supported features should be documented in that sense, except where API changes might result in differences.

**Comment by elof** [comment]
@davidknaack sorry, my comment wasn't very clear. I mean that I would like to up-date the readme in the repo to include more references to what the SDK supports. Meaning, if it supports querying I would like to add that to the readme.

**Comment by davidknaack** [comment]
@elof Ah, yes, I see what you mean, the README only mentions querying briefly and doesn't include a section on that. It also doesn't mention scoped key support, some notes about that would be useful.
I'd have to do a little digging to find more.
