### ISSUE TITLE
ScopedKey.Encrypt System.Convert.ToChar

### ISSUE THREAD

**Issue by jefersonmanjos** [keenlabs/keen-sdk-net#28]
Try to create scropedkey throw exception   Message=Value was either too large or too small for a character in function ScopedKey.AddPadding(String text).
` dynamic secOps = new ExpandoObject();

            IDictionary<string, object> filter = new ExpandoObject();
            filter.Add("property_name", "account_id");
            filter.Add("operator", "eq");
            filter.Add("property_value", 123);
            secOps.filters = new List<object>() { filter };
            secOps.allowed_operations = new List<string>() { "read" };

            var scopedKey = ScopedKey.Encrypt(_keenioMasterKey, (object)secOps);`

**Comment by davidknaack** [comment]
What is the length of the value in _keenioMasterKey?
It should be 32, the length of a Keen.io master key value.

**Comment by dkador** [comment]
David, we changed something in the API here for new Keen customers. New keys are 64 characters. And instead of using the master key as the AES-256 key, we first convert the master key from hex to bytes and use the bytes. So there is definitely stuff to fix here.

**Comment by jefersonmanjos** [comment]
Dears, I change class ScopedKey to convert from hex to bytes. And it work fine. The code is like this:

` public static string Encrypt(string apiKey, object secOptions, string IV = "")
        {
            var secOptionsJson = JObject.FromObject(secOptions ?? new object()).ToString();
            var key = StringToByteArray(apiKey);
            return EncryptString(key, secOptionsJson, IV);
        }
        public static byte[] StringToByteArray(String hex)
        {
            int NumberChars = hex.Length;
            byte[] bytes = new byte[NumberChars / 2];
            for (int i = 0; i < NumberChars; i += 2)
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            return bytes;
        }`

**Comment by jefersonmanjos** [comment]
I Have a second problem. When I add two or more filters, server response API Key is invalid. But, with one filter, everything work fine.

**Comment by davidknaack** [comment]
@jefersonmanjos I've updated the source to support both the old 32 char keys and the new 64 char keys. Can you pull the latest from github to see if this update resolves your problem with the key, and also recheck the problem you were having with adding two or more filters?
