### ISSUE TITLE
PCL has a dependency on a non-existent version of PCLStorage

### ISSUE THREAD

**Issue by CliffCawley** [keenlabs/keen-sdk-net#31]
https://www.nuget.org/packages/KeenClient/0.3.12
Lists PCLStorage (>= 1.0.6)

However https://www.nuget.org/packages/PCLStorage/ only goes to PCL Storage - Portable Storage APIs 1.0.2

So when I add the nuget package it fails because it can't find 1.0.6

I'm attempting to add to a Xamarin Forms PCL project

**Comment by davidknaack** [comment]
Hi @CliffCawley , thanks for the report! 

There was a typo in the version number on the NuGet package. Could you install this unlisted package and confirm whether it fixes the problem for you?

`Install-Package KeenClient -Version 0.3.13`

**Comment by CliffCawley** [comment]
Thanks, finally got a chance to revisit this and 0.3.13 works great :)

**Comment by CliffCawley** [comment]
Although I am now having another problem when trying to add an event:

```
			var prjSettings = new ProjectSettingsProvider("~REMOVED~", writeKey: "~REMOVED~");
			var keenClient = new KeenClient(prjSettings);
			keenClient.AddGlobalProperty("clienttype", "mobile");

						// Build an event object
			var aPurchase = new
			{
				category = "magical animals",
				username = "hagrid",
				price = 7.13,
				payment_type = "information",
				animal_type = "norwegian ridgeback dragon",
				user_ip = "8.8.8.8",
				ua = "Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; DigExt; .NET CLR 1.0.3705)"
			};

			// send the event
 			keenClient.AddEvent("purchases", aPurchase);
```

the AddEvent call asserts with: 
```
System.BadImageFormatException was thrown: Could not resolve field token 0x04000219
```

**Comment by davidknaack** [comment]
I'm going to close this dependency issue, can you post the BadImageFormatException problem as a new issue?
