### ISSUE TITLE
.NET 3.5 version of SDK duplicates code from portable library and .NET 4.0 library.

### ISSUE THREAD

**Issue by baumatron** [keenlabs/keen-sdk-net#36]
The .NET 3.5 project contains what is mostly copy and pasted code from the more recent library (or vice-versa). The project should be refactored so as to not duplicate any code. CLR features not supported by 3.5 should be either removed from the new library, implemented as a component that can vary between the SDK versions, or implemented as a shim or derived class in the .NET 4/4.5/portable library.

**Comment by baumatron** [comment]
As part of the push for netstandard, we can eventually deprecate the .NET 3.5 library. It mainly exists to support Unity, which will be moving to support netstandard hopefully with their next release.

**Comment by masojus** [comment]
This is fixed in PR #135 with commit 96ee7b5
