### ISSUE TITLE
Automated Unit Tests Have Poor Coverage

### ISSUE THREAD

**Issue by baumatron** [keenlabs/keen-sdk-net#37]
Unit tests don't actually exercise core components of the SDK. The EventCollection and Event classes are basically untested by automated testing.

A solution would be to do away with the UseMocks flag found in the tests, and use a mock HTTP protocol handler that would validate requests and provide canned responses.

**Comment by masojus** [comment]
For the purposes of `#dotnetsummer` work we can split this up into more specific tasks if someone is interested. This might even go hand in hand with writing tests for work as it's ported to dotnetstandard.

**Comment by baumatron** [comment]
Been pushing tests to `increase_coverage_2`, which is a WIP.

**Comment by masojus** [comment]
Marking as closed with PR #127 since code coverage is increased quite a bit. There's still more that can be done, but that can be handled in newer specific issues.
