### ISSUE TITLE
Keen.IO on .NET 3.5 framework (Unity3D)

### ISSUE THREAD

**Issue by pebelloncik** [keenlabs/keen-sdk-net#5]
Hello, 

I'm looking into integrating Keen.IO in a PC/OSX/WebPlayer Unity3D app. I grabbed your SDK but it's written in .NET 4.0, while my Unity3D 3.5 environment is stuck in what seems to be .NET 3.5-ish, maybe older.

I'm thinking of rewriting the code and attempt to downgrade frameworks, yet being unfamiliar with new C# and .NET features the task seems daunting to me.

Any advice, suggestion on how to go about it?
What about the SDK's dependencies, could they be downgraded too?

**Comment by davidknaack** [comment]
I added support for .Net 3.5 as a feature-reduced version a while back, left this issue open for questions/comments. Closing now; anyone please open a new issue if you encounter problems.
