### ISSUE TITLE
Port/rewrite EventCachePortable for new netstandard PCL

### ISSUE THREAD

**Issue by baumatron** [keenlabs/keen-sdk-net#65]
This class is broken, and references API's that don't seem to be included in the netstandard API surface. First, confirm that the API's it relies on aren't included in netstandard2.0. If that's the case, it needs to be re-written targeting a netstandard API surface, along with robust unit tests. Otherwise, fix it and provide some good unit tests.

See https://github.com/keenlabs/keen-sdk-net/issues/21

**Comment by baumatron** [comment]
https://www.nuget.org/packages/PCLStorage.Standard/ might be useful.

**Comment by Donistivanov** [comment]
I will work on this

**Comment by baumatron** [comment]
Taking a stab at porting the file io stuff.

**Comment by baumatron** [comment]
I've made some really good progress using .net standard API's. I'll hopefully be able to wrap up the simple port tomorrow and then be able to move on to the threading issues.

**Comment by baumatron** [comment]
Merged to `dotnetsummer` from #121.
