### ISSUE TITLE
Port simple/metric analyses to netstandard binary

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#68]
This encompasses the work to perform single-analysis queries like count, minimum, sum, average, etc. This will involve porting a portion of `Queries.cs`, namely the `Queries.Metric()` overloads and related code, as well as the relevant parts of KeenClient that forward down to this implementation.

See the API Ref for more information:
https://keen.io/docs/api/#analyses

**Comment by Pothulapati** [comment]
Once all the PR's in the "In Progress" dashboard are merged, I would like to work on this.

**Comment by masojus** [comment]
@Pothulapati Don't worry about Issue #65 as it shouldn't impede you much with getting the analysis fundamentals ported. Go ahead and get up-to-date with the `dotnetsummer` branch and feel free to get started. Let me know if you need any assistance.

**Comment by masojus** [comment]
Fixed in PR #112, see commit 922ce2d
