### ISSUE TITLE
Port Multi-Analysis to netstandard binary

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#69]
This would be the work layered on top of Issue #68 to add multi-analysis functionality. This would touch code in `Queries.cs`, the wrapper code in `KeenClient.cs` as well as some other code in the `Keen.Core.Query` namespace.

See the API ref for more information: https://keen.io/docs/api/#multi-analysis

**Comment by baumatron** [comment]
Working on this.

**Comment by baumatron** [comment]
Edit: Not working on this... need to get #68 done first.

**Comment by masojus** [comment]
Fixed in PR #112, see commit 922ce2d
