### ISSUE TITLE
Port Funnel analysis to netstandard binary

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#70]
Work to port the code in `Queries.cs`, the wrappers in `KeenClient.cs` and the relevant classes in the `Keen.Core.Query` namespace to the new netstandard binary.

See the API ref for more info: https://keen.io/docs/api/#funnels

**Comment by Donistivanov** [comment]
I will work on this based on https://github.com/keenlabs/keen-sdk-net/issues/61#issuecomment-318632865

**Comment by masojus** [comment]
Fixed in PR #112, see commit 922ce2d
