### ISSUE TITLE
netstandard test binary

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#74]
Right now we only test the PCL via the 4.5 and 3.5 test projects. If we manage to move all or most code into a binary targeting netstandard, we should start testing directly and port existing tests, plus expand on test in that binary.

Creating this binary should go along with or immediately after Issue #60

**Comment by jongalloway** [comment]
I'll take this one. Per slack discussion, I'm creating a Keen.NetStandard.Test class library.

**Comment by masojus** [comment]
Fixed by PR #102, see commits 4974a5b and 01c8cfc.
