### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by sjparkinson** [keenlabs/keen-sdk-net#8]
Hi there, I'm getting the following issue when integrating the Keen client in my project:

```
Assembly generation failed -- Referenced assembly 'Keen' does not have a strong name
```

> When you compile an assembly with a strong name, any referenced assemblies must also have strong names.

From http://support.microsoft.com/kb/313666.

This occurs on build after including the 0.3.1 KeenClient via NuGet.

Might be a `wontfix` but figured it's worth mentioning.

Here's a informative post on the issue http://www.codingblocks.net/programming/strongly-named-assemblies-in-nuget/.

**Comment by FantasticFiasco** [comment]
I would love to have keen-sdk-net strong named as well. I can't use strong names if you won't use them. And about the issue with private keys, I am not sure one has to have the key private. The open source project I am writing extensions for (Serilog) has chosen to not have their strong name password protected.
